/*
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package goflagr

type Distribution struct {

	Id int64 `json:"id,omitempty"`

	Percent int64 `json:"percent"`

	Bitmap string `json:"bitmap,omitempty"`

	VariantKey string `json:"variantKey"`

	VariantID int64 `json:"variantID"`
}
