/*
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package goflagr

type Flag struct {

	Id int64 `json:"id,omitempty"`

	Description string `json:"description"`

	Enabled bool `json:"enabled"`

	Segments []Segment `json:"segments,omitempty"`

	Variants []Variant `json:"variants,omitempty"`

	// enabled data records will get data logging in the metrics pipeline, for example, kafka.
	DataRecordsEnabled bool `json:"dataRecordsEnabled"`
}
