/*
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package goflagr

type Segment struct {

	Id int64 `json:"id,omitempty"`

	Description string `json:"description"`

	Constraints []Constraint `json:"constraints,omitempty"`

	Distributions []Distribution `json:"distributions,omitempty"`

	Rank int64 `json:"rank"`

	RolloutPercent int64 `json:"rolloutPercent"`
}
